apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab21
  labels:
    app: frontend-lab21
spec:
  selector:
    matchLabels:
      app: frontend-lab21
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab21
    spec:
      containers:
        - name: frontend-lab21
          image: kurafore/frontend-lab21
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
